### ISSUE TITLE
Typo of "About"

### ISSUE THREAD

**Issue by kkdai** [golangtw/gophercon.github.io#3]
AS-IS:

Gopher Conference 自 2020 年發起，由 Golang Taipei 社群舉辦，長期投身推廣 Golang 程式語言與相關技術，希望引領更多軟體從業人員使用 Golang 語言，對 Golang 有興趣的朋友可以一同參與社群。

....

Gopher Conference is a conference held by Golang Taipei User Group since 2020. It's aim is promoting Go language and Go's communities. The event is held with talks, sponsor, and communities booths. Whoever you are a Golang coder, open source promoter, or even a newcomer, we sincerely welcome you to be part of GopherCon!

TO-BE:

Gopher Conference `Taiwan` 自 2020 年發起，由 Golang Taipei 社群舉辦，長期投身推廣 Golang 程式語言與相關技術，希望引領更多軟體從業人員使用 Golang 語言，對 Golang 有興趣的朋友可以一同參與社群。

...

Gopher Conference `Taiwan` is a conference held by Golang Taipei User Group since 2020. Its aim is to promote Go language and Go's communities. The event is held with talks, sponsors, and community booths. Whoever you are a Golang coder, open source promoter, or even a newcomer, we sincerely welcome you to be part of GopherCon!

**Comment by chenyunchen** [comment]
Update taiwan postfix:
golangtw/gophercon2020#40
