### ISSUE TITLE
Typo for "Q&A"

### ISSUE THREAD

**Issue by kkdai** [golangtw/gophercon.github.io#4]
AS-IS:
Q1. 什麼樣的人適合參與 GopherCon ？
A1. Gopher Conference 致力於 Golang 的推廣，無論是已經身在資訊領域，或是還沒踏進資訊領域的學生，只要想一窺資訊世界，都適合來參與！

-----
TO-BE:
Q1. 什麼樣的人適合參與 GopherCon TW？
A1. Gopher Conference Taiwan 致力於 Golang 的推廣，無論是已經身在資訊領域，或是還沒踏進資訊領域的學生，只要想一窺資訊世界，都適合來參與！

**Comment by chenyunchen** [comment]
Update taiwan postfix:
golangtw/gophercon2020#40
